### ISSUE TITLE
Refactoring: New layout, design and data storage features

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz-config#578]
Based on the discussion between @anders-kiaer, @HansKallekleiv, @jorgenherje and me, here is a short summary of the results:

**Short term changes**
- [X] Icon used for collapsing expanded views should be changed to 
![image](https://user-images.githubusercontent.com/69145689/153868452-8b2d1260-4936-4474-8bfe-fb1723843bee.png)
- [X] Switch from `bootstrap's` modal view to `MaterialUI's` draggable dialog (https://mui.com/components/dialogs/#draggable-dialog) 
- [x] Implement a wrapper around each view in a plugin in order to provide an expand mechanism

**Medium term changes**
- [x] Make settings related to a particular view available via a gear icon button in the view's wrapper options
![image](https://user-images.githubusercontent.com/69145689/153870126-8649ad36-e3d7-456b-aaf1-ae433749cdeb.png)
- [x] Consider replacing expand/collapse wrapper with [`Accordion`](https://mui.com/components/accordion/), [eds also have one](https://eds-storybook-react.azurewebsites.net/?path=/docs/surfaces-accordion--simple)
- [x] Move plugin settings to a drawer that can be pinned (like the main menu)
- [x] With a settings menu that has ownership to view layout, we can limit the current loading indicator to only relevant view (using e.g. functionality from https://dash.plotly.com/loading-states), and remove the global app loading indicator (https://github.com/equinor/webviz-config-equinor/blob/15f159132920314c48223421ad66a8bb80eca85a/webviz_config_equinor/assets/equinor_theme.css#L103-L131).

**Long term changes**
- [ ] Use URL to share the exact same view with all set parameters (ask Dash/Plotly to implement a URL sharing feature)
- [x] Make it possible to implement a plugin group, i.e. one plugin with the same data but with different views that share the data - the views can either be accessible as subpages in the menu or as tabs in the plugin
    - Should tabs only be used when settings are shared between different views and subpages if only data but no settings are shared?
- [ ] Store view settings in browser's client-side storage (e.g. menu's pinned state or expand/collapse state of settings' groups) https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

**Comment by jorgenherje** [comment]
Good summary! Only one question: should the last bulletpoint `Move plugin settings to a drawer that can be pinned (like the main menu)` be a short term or medium term task instead?

**Comment by rubenthoms** [comment]
Closing this since most of the tasks have been completed in #599 and https://github.com/equinor/webviz-core-components/pull/201. Moved the remaining tasks to #600 and #601.
